line_length: 300

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- RxSwift

identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
